version: "2"

services:
  node:
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    volumes:
      - /home/app/quiz-frontend
  nginx:
      restart: always
      build: ./compose/nginx
      volumes_from:
        - node
      depends_on:
        - node
      ports:
        - "80:80"

